proto: Update generated Rust code
Update the  Rust code that is generated from the `.proto` files, since
newer `rust-protobuf` releases throw errors like:

    error: use of deprecated struct `protobuf::lazy::Lazy`: Please regenerate .rs files from .proto files to use newer APIs
       --> src/../proto/secret.rs:863:40
        |
    863 | static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy::INIT;
        |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^