Update a deprecated protobuf function
Replace a function that has been deprecated in newer `rust-protobuf`
releases with the suggested one. The exact error that the compiler
throws is:

    error: use of deprecated function `protobuf::parse_from_bytes`: Use Message::parse_from_bytes instead
       --> src/secret.rs:217:15
        |
    217 |         match protobuf::parse_from_bytes(&buf) {
        |               ^^^^^^^^^^^^^^^^^^^^^^^^^^